services:
  - type: web
    name: cinematch-ai
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: TMDB_API_KEY
        value: 6510a58a97f15e281d23de77c93e42ba
      - key: SECRET_KEY
        value: cinematchAi_syntecxhub_2026_secure

